# Generated by Django 5.1.7 on 2025-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veterinaria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="doctor",
            name="years_of_experience",
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
